#!/bin/sh
#
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 <input_video_file> <output_file> <start H:MM:SS> <end H:MM:SS>" >&2
  echo "Extracts the segment from the <input_video_file>." >&2
  exit 1
fi
set -x
ffmpeg -hide_banner -i "$1" -c copy -ss $3 -to $4 "$2"

# ffmpeg -hide_banner -i in.mp4 -c copy -map_metadata 0 -ss 3:00 -to 6:05 out.mp4
# ffmpeg -hide_banner -i x.mp4
# Handles subtitles:
# ffmpeg -hide_banner -i "$1" -vcodec copy -acodec copy -scodec copy -ss $3 -to $4 -f mpegts "$2"
# Passes through metadata, maybe breaks subtitles:
# ffmpeg -hide_banner -i "$1" -c copy -ss $3 -to $4 "$2"
