#!/bin/sh
# Cuts a video file $1 and creates new file $2, copying from H:M:S.S $3 to $4
#
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 <input_video_file> <output filename> <start time> <end time>" >&2
  echo "Extracts the segment from the <input filename> video file." >&2
  exit 1
fi
set -x
ffmpeg -hide_banner -i "$1" -vcodec copy -acodec copy -scodec copy -ss $3 -to $4 -f mpegts "$2"

# ffmpeg -hide_banner -i BBC_London_Late_News_-_71._2021-06-22_m000x911_original.mp4 -c copy -map_metadata 0 -ss 3:00 -to 6:05 2021-06-22-WindrushDay.mp4
# ffmpeg -hide_banner -i BBC_London_Late_News_-_71._2021-06-22_m000x911_original.mp4 -c copy -map_metadata 0 -ss 4:41 -to 5:25 x.mp4
# ffmpeg -hide_banner -i x.mp4
