#!/bin/sh
#
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <file pattern match> <output filename>" >&2
  echo "Concatenates video files <file pattern match> and creates a single video <output filename>." >&2
  exit 1
fi

set -x

#ls $1 | awk '{print "file "$0}' | ffmpeg -hide_banner -f concat -safe 0 -protocol_whitelist "file,pipe" -i - -vcodec copy -acodec copy -scodec copy -f mpegts $2
ls $1 | awk '{print "file "$0}' >tmp.list
ffmpeg -hide_banner -f concat -safe 0 -i tmp.list -c copy $2
rm tmp.list

# ls $1 | awk '{print "file "$0}' | ffmpeg -hide_banner -f concat -safe 0 -protocol_whitelist "file,pipe" -i - -vcodec copy -acodec copy -scodec copy -f mpegts $2 ## original
# ffmpeg -f concat -safe 0 -i l -c copy x.mp4 ## this worked
